export enum ItemType {
   /* Basic */
   CONSUMABLE,
   EQUIPABLE,
   STACKABLE,
   MISCELLANEOUS,
   DEPLOYABLE,

   DRINK,
   BEVERAGE,

   /* Document types */
   IDENTITY_DOCUMENT,
   BADGE,
   DRIVING_LICENSE,
   CREDIT_CARD,
   FISHING_LICENSE,
   SAILING_LICENSE,
   HUNTING_LICENSE,
   WEAPON_LICENSE,

   /* Weaponn types */
   WEAPON_MELEE,
   WEAPON_HANDGUN,
   WEAPON_SUBMACHINE,
   WEAPON_SHOTGUN,
   WEAPON_ASSAULT_RIFLE,
   WEAPON_SNIPER,
   WEAPON_LIGHT_MACHINEGUN,
   WEAPON_GRENADE,
   WEAPON_MISCELLANEOUS,

   ARMOUR,

   JERRY_CAN,
   FISHING_ROD,

   UTILITY,
   TOOL,
   ELECTRONIC_DEVICE,
   DEVICE_SMARTPHONE,
   DEVICE_HANDHELD_RADIO,

   AMMUNITION,

   PRODUCT_GROCERY,
   PRODUCT_GAS_STATION,
   PRODUCT_CLOTHING_STORE,
   PRODUCT_AMMUNITION,
   PRODUCT_RESTAURANT,
}
