export const enum ProcedureKey {
  BROWSER_SHOW_GAME_INTERFACE = 'browser_showGameInterface',
  BROWSER_HIDE_GAME_INTERFACE = 'browser_hideGameInterface',
  CLIENT_PLAYER_SHOW_INTERFACE = 'client_playerShowInterface',
  CLIENT_PLAYER_HIDE_INTERFACE = 'client_playerHideInterface',
  BROWSER_NOTIFICATION = 'browser_notification',

  BROWSER_AUTHORIZATION_REMEMBER = 'browser_authSuggestion',

  SERVER_PLAYER_CREATE_ACCOUNT = 'server_playerCreateAccount',
  SERVER_PLAYER_AUTHORIZE = 'server_playerAuthorize',
  SERVER_PLAYER_AUTHORIZE_DISCORD = 'server_playerAuthorizeDiscord',
  SERVER_PLAYER_CREATE_CHARACTER = 'server_playerCreateCharacter',

  SERVER_PLAYER_SELECT_CHARACTER = 'server_playerSelectCharacter',

  CLIENT_TOGGLE_PLAYER_AUTHORIZATION = 'client_togglePlayerAuthorization',
  CLIENT_TOGGLE_BAN_INFO = 'client_toggleBanInfo',
  CLIENT_AUTHORIZATION_REMEMBER_ME = 'client_authorizationRememberMe',
  CLIENT_AUTHORIZATION_DISCORD = 'client_authorizationDiscord',
  CLIENT_TOGGLE_CHARACTER_CREATOR = 'client_toggleCharacterCreator',
  CLIENT_CREATOR_UPDATE_HEAD_BLEND_DATA = 'client_creatorUpdateHeadBlendData',
  CLIENT_CREATOR_CHANGE_PED_MODEL = 'client_creatorChangePedModel',

  CLIENT_CREATOR_UPDATE_FACE_FEATURE = 'client_creatorUpdateFaceFeature',
  CLIENT_CREATOR_UPDATE_BEARD = 'client_creatorUpdateBeard',
  CLIENT_CREATOR_UPDATE_HEAD_OVERLAY = 'client_creatorUpdateHeadOverlay',
  CLIENT_CREATOR_CHANGE_EYE_COLOR = 'client_creatorChangeEyeColor',
  CLIENT_CREATOR_UPDATE_HAIR = 'client_creatorChangeHair',
  CLIENT_CREATOR_CHANGE_OUTFIT = 'client_creatorChangeOutfit',

  SERVER_PLAYER_GET_VARIABLE = 'server_playerGetVariable',
  SERVER_PLAYER_SET_VARIABLE = 'server_playerSetVariable',

  CLIENT_GET_NEARBY_PLAYERS = 'client_getNearbyPlayers',
  CLIENT_FILTER_PLAYERS = 'client_filterPlayers',

  BROWSER_SET_INVENTORY = 'browser_setInventory',
  BROWSER_INVENTORY_UPDATE_ITEM = 'browser_inventoryUpdateItem',
  BROWSER_INVENTORY_ADD_ITEM = 'browser_inventoryAddItem',
  BROWSER_INVENTORY_REMOVE_ITEM = 'browser_inventoryRemoveItem',
  CLIENT_PLAYER_DROP_ITEM = 'client_playerDropItem',
  SERVER_PLAYER_DROP_ITEM = 'server_playerDropItem',
  SERVER_PLAYER_PICKUP_ITEM = 'server_playerPickupItem',
  SERVER_PLAYER_CHANGE_ITEM_SLOT = 'server_playerChangeItemSlot',
  SERVER_PLAYER_SELECT_ITEM = 'server_playerSelectItem',
  SERVER_PLAYER_SPLIT_ITEM = 'server_playerSplitItem',
  SERVER_PLAYER_USE_ITEM = 'server_playerUseItem',
  SERVER_P2P_GIVE_ITEM = 'server_playerGiveItemToPlayer',
  SERVER_PLAYER_DESTROY_ITEM = 'server_playerDestroyItem',
  SERVER_PLAYER_EQUIP_ITEM =  'server_playerEquipItem',

  SERVER_PLAYER_WEAPON_RELOAD = 'server_playerWeaponReload',

  SERVER_PLAYER_SAVE_WEAPON = 'server_playerSaveWeapon',
  BROWSER_UPDATE_LOCATION = 'browser_updateLocation',
  BROWSER_UPDATE_CASH = 'browser_updateCash',
  BROWSER_UPDATE_SELECTED_ITEM_ID = 'browser_updateSelectedItemId',

  BROWSER_SET_PLAYER_REMOTE_ID = 'browser_setPlayerRemoteId',
  CLIENT_PLAYER_ENTER_VEHICLE = 'client_playerEnterVehicle',
  SERVER_PLAYER_TOGGLE_VEHICLE_ENGINE = 'server_playerToggleVehicleEngine',
  BROWSER_UPDATE_VEHICLE_HUD = 'browser_updateVehicleHud',
  SERVER_PLAYER_UPDATE_VEHICLE_DATA = 'server_playerUpdateVehicleData',
  SERVER_PLAYER_LOCK_VEHICLE = 'server_playerLockVehicle',
  SERVER_PLAYER_TOGGLE_VEHICLE_INDICATOR = 'server_playerToggleVehicleIndicator',

  BROWSER_INIT_OFFER = 'browser_initOffer',
  SERVER_PLAYER_OFFER_RESPONSE = 'server_playerOfferResponse',
  CLIENT_PLAYER_TOGGLE_BANK_MENU = 'client_playerToggleBankMenu',

  SERVER_PLAYER_CREATE_SAVING_ACCOUNT = 'server_playerCreateSavingAccount',
  CLIENT_PLAYER_USE_BANK_CARD = 'client_playerUseBankCard',
  BROWSER_ATM_INIT = 'browser_atmInit',
  SERVER_PLAYER_BANK_GET_TRANSACTIONS = 'server_playerBankGetTransactions',
  SERVER_PLAYER_DEPOSIT_MONEY = 'server_playerDepositMoney',
  SERVER_PLAYER_WITHDRAW_MONEY = 'server_playerWithdrawMoney',
  SERVER_PLAYER_TRANSFER_MONEY = 'server_playerTransferMoney',
  SERVER_PLAYER_BANK_GET_ACCOUNTS = 'server_playerBankGetAccounts',
  SERVER_PLAYER_BANK_GET_ACCOUNT = 'server_playerBankGetAccount',
  CLIENT_PLAYER_CLOSE_ATM = 'client_playerToggleAtm',
  SERVER_PLAYER_BANK_GET_CARDS = 'server_playerBankGetCards',
  SERVER_PLAYER_BANK_DEACTIVATE_CARD = 'server_playerBankDeactivateCard',
  SERVER_PLAYER_BANK_CREATE_CARD = 'server_playerBankCreateCard',

  CLIENT_TOGGLE_ANIMATION_MENU = 'client_toggleAnimationMenu',
  SERVER_PLAYER_DAMAGE = 'server_playerGetDamage',
  SERVER_PLAYER_GET_WOUND_TIMER = 'server_playerGetWoundTimer',
  BROWSER_SET_PLAYER_DAMAGES  = 'browser_setPlayerDamages',
  CLIENT_PLAYER_TOGGLE_DAMAGE_INFO = 'client_playerToggleDamageInfo',

  CLIENT_TOGGLE_ORGANIZATION_PANEL = 'client_toggleOrganizationPanel',
  SERVER_PLAYER_GET_ORGANIZATIONS = 'server_playerGetOrganizations',
  SERVER_GET_ORGANIZATION = 'server_getOrganization',
  SERVER_PLAYER_CREATE_ORGANIZATION = 'server_playerCreateOrganization',
  SERVER_GET_ORGANIZATION_MEMBERS = 'server_getOrganizationMembers',
  SERVER_ORGANIZATION_MEMBER_UNINVITE = 'server_organizationMemberUninvite',
  SERVER_ORGANIZATION_MEMBER_UPDATE = 'server_organizationMemberUpdate',
  SERVER_CREATE_ORGANIZATION_RANK = 'server_createOrganizationRank',
  SERVER_ORGANIZATION_MEMBER_INVITE = 'server_organizationMemberInvite',
  SERVER_ORGANIZATION_RANK_DELETE = 'server_organizationRankDelete',
  BROWSER_SET_ORGANIZATION_ID = 'browser_setOrganizationId',
  SERVER_ORGANIZATION_RANK_UPDATE = 'server_organizationRankUpdate',

  CLIENT_PLAYER_TOGGLE_NO_CLIP = 'client_playerToggleNoClip',

  BROWSER_SET_HANDHELD_RADIO = 'browser_setHandheldRadio',
  SERVER_HANDHELD_RADIO_UPDATE = 'server_handheldRadioUpdate',

  BROWSER_SET_BAN_INFO = 'browser_setBanInfo',

  SERVER_PROPERTY_CREATE = 'server_propertyCreate',
  CLIENT_TOGGLE_PROPERTY_INFO = 'client_togglePropertyInfo',
  BROWSER_SET_PROPERTY_INFO = 'browser_setPropertyInfo',
}
