export const enum ProcedureKey {
  BROWSER_SHOW_GAME_INTERFACE = 'browser_showGameInterface',
  BROWSER_HIDE_GAME_INTERFACE = 'browser_hideGameInterface',
  CLIENT_PLAYER_SHOW_INTERFACE = 'client_playerShowInterface',
  CLIENT_PLAYER_HIDE_INTERFACE = 'client_playerHideInterface',
  BROWSER_NOTIFICATION = 'browser_notification',

  BROWSER_AUTHORIZATION_REMEMBER = 'browser_authSuggestion',

  SERVER_PLAYER_CREATE_ACCOUNT = 'server_playerCreateAccount',
  SERVER_PLAYER_AUTHORIZE = 'server_playerAuthorize',
  SERVER_PLAYER_AUTHORIZE_DISCORD = 'server_playerAuthorizeDiscord',
  SERVER_PLAYER_CREATE_CHARACTER = 'server_playerCreateCharacter',

  SERVER_PLAYER_SELECT_CHARACTER = 'server_playerSelectCharacter',

  CLIENT_TOGGLE_PLAYER_AUTHORIZATION = 'client_togglePlayerAuthorization',
  CLIENT_TOGGLE_BAN_INFO = 'client_toggleBanInfo',
  CLIENT_AUTHORIZATION_REMEMBER_ME = 'client_authorizationRememberMe',
  CLIENT_AUTHORIZATION_DISCORD = 'client_authorizationDiscord',
  CLIENT_TOGGLE_CHARACTER_CREATOR = 'client_toggleCharacterCreator',
  CLIENT_CREATOR_UPDATE_HEAD_BLEND_DATA = 'client_creatorUpdateHeadBlendData',
  CLIENT_CREATOR_CHANGE_PED_MODEL = 'client_creatorChangePedModel',

  CLIENT_CREATOR_UPDATE_FACE_FEATURE = 'client_creatorUpdateFaceFeature',
  CLIENT_CREATOR_UPDATE_BEARD = 'client_creatorUpdateBeard',
  CLIENT_CREATOR_UPDATE_HEAD_OVERLAY = 'client_creatorUpdateHeadOverlay',
  CLIENT_CREATOR_CHANGE_EYE_COLOR = 'client_creatorChangeEyeColor',
  CLIENT_CREATOR_UPDATE_HAIR = 'client_creatorChangeHair',
  CLIENT_CREATOR_CHANGE_OUTFIT = 'client_creatorChangeOutfit',

  SERVER_PLAYER_GET_VARIABLE = 'server_playerGetVariable',
  SERVER_PLAYER_SET_VARIABLE = 'server_playerSetVariable',

  CLIENT_GET_NEARBY_PLAYERS = 'client_getNearbyPlayers',
  CLIENT_FILTER_PLAYERS = 'client_filterPlayers',

  BROWSER_SET_INVENTORY = 'browser_setInventory',
  BROWSER_INVENTORY_UPDATE_ITEM = 'browser_inventoryUpdateItem',
  BROWSER_INVENTORY_ADD_ITEM = 'browser_inventoryAddItem',
  BROWSER_INVENTORY_REMOVE_ITEM = 'browser_inventoryRemoveItem',
  CLIENT_PLAYER_DROP_ITEM = 'client_playerDropItem',
  SERVER_PLAYER_DROP_ITEM = 'server_playerDropItem',
  SERVER_DROPPED_ITEM_SYNC = 'server_droppedItemSync',
  SERVER_PLAYER_PICKUP_ITEM = 'server_playerPickupItem',
  SERVER_PLAYER_CHANGE_ITEM_SLOT = 'server_playerChangeItemSlot',
  SERVER_PLAYER_SELECT_ITEM = 'server_playerSelectItem',
  SERVER_PLAYER_SPLIT_ITEM = 'server_playerSplitItem',
  SERVER_PLAYER_USE_ITEM = 'server_playerUseItem',
  SERVER_P2P_GIVE_ITEM = 'server_playerGiveItemToPlayer',
  SERVER_PLAYER_DESTROY_ITEM = 'server_playerDestroyItem',
  SERVER_PLAYER_EQUIP_ITEM = 'server_playerEquipItem',

  SERVER_PLAYER_WEAPON_RELOAD = 'server_playerWeaponReload',

  SERVER_PLAYER_SAVE_WEAPON = 'server_playerSaveWeapon',
  BROWSER_UPDATE_LOCATION = 'browser_updateLocation',
  BROWSER_UPDATE_CASH = 'browser_updateCash',
  BROWSER_UPDATE_SELECTED_ITEM_ID = 'browser_updateSelectedItemId',

  BROWSER_SET_PLAYER_REMOTE_ID = 'browser_setPlayerRemoteId',
  SERVER_PLAYER_TOGGLE_VEHICLE_ENGINE = 'server_playerToggleVehicleEngine',
  SERVER_GET_VEHICLE_OPTIONS = 'server_getVehicleOptions',
  SERVER_VEHICLE_OPTION = 'server_vehicleOption',
  SERVER_PLAYER_TOGGLE_SEATBELT = 'server_playerToggleSeatbelt',
  BROWSER_UPDATE_VEHICLE_HUD = 'browser_updateVehicleHud',
  SERVER_PLAYER_UPDATE_VEHICLE_DATA = 'server_playerUpdateVehicleData',
  SERVER_PLAYER_LOCK_VEHICLE = 'server_playerLockVehicle',
  SERVER_PLAYER_TOGGLE_VEHICLE_INDICATOR = 'server_playerToggleVehicleIndicator',
  SERVER_VEHICLE_TOGGLE_TRUNK = 'server_vehicleToggleTrunk',
  SERVER_VEHICLE_TOGGLE_HOOD = 'server_vehicleToggleHood',
  BROWSER_SET_VEHICLE = 'browser_setVehicle',
  SERVER_GET_VEHICLE_TRUNK = 'server_getVehicleTrunk',
  SERVER_VEHICLE_TRUNK_PUT_ITEM = 'server_vehicleTrunkPutItem',
  SERVER_VEHICLE_TRUNK_TAKE_ITEM = 'server_vehicleTrunkTakeItem',
  CLIENT_GET_VEHICLE_STATS = 'client_getVehicleStats',

  BROWSER_INIT_OFFER = 'browser_initOffer',
  SERVER_PLAYER_OFFER_RESPONSE = 'server_playerOfferResponse',
  CLIENT_PLAYER_TOGGLE_BANK_MENU = 'client_playerToggleBankMenu',

  SERVER_PLAYER_CREATE_SAVING_ACCOUNT = 'server_playerCreateSavingAccount',
  CLIENT_PLAYER_USE_BANK_CARD = 'client_playerUseBankCard',
  BROWSER_ATM_INIT = 'browser_atmInit',
  SERVER_BANK_GET_TRANSACTIONS = 'server_bankGetTransactions',
  SERVER_PLAYER_DEPOSIT_MONEY = 'server_playerDepositMoney',
  SERVER_PLAYER_WITHDRAW_MONEY = 'server_playerWithdrawMoney',
  SERVER_PLAYER_TRANSFER_MONEY = 'server_playerTransferMoney',
  SERVER_PLAYER_BANK_GET_ACCOUNTS = 'server_playerBankGetAccounts',
  SERVER_PLAYER_BANK_GET_ACCOUNT = 'server_playerBankGetAccount',
  CLIENT_PLAYER_CLOSE_ATM = 'client_playerToggleAtm',
  SERVER_PLAYER_BANK_GET_CARDS = 'server_playerBankGetCards',
  SERVER_PLAYER_BANK_DEACTIVATE_CARD = 'server_playerBankDeactivateCard',
  SERVER_PLAYER_BANK_CREATE_CARD = 'server_playerBankCreateCard',
  SERVER_BANK_UPDATE_PHONE = 'server_bankUpdatePhone',

  CLIENT_TOGGLE_ANIMATION_MENU = 'client_toggleAnimationMenu',
  SERVER_PLAYER_DAMAGE = 'server_playerGetDamage',
  SERVER_PLAYER_GET_WOUND_TIMER = 'server_playerGetWoundTimer',
  BROWSER_SET_PLAYER_DAMAGES = 'browser_setPlayerDamages',
  CLIENT_PLAYER_TOGGLE_DAMAGE_INFO = 'client_playerToggleDamageInfo',

  CLIENT_TOGGLE_ORGANIZATION_PANEL = 'client_toggleOrganizationPanel',
  SERVER_PLAYER_GET_ORGANIZATIONS = 'server_playerGetOrganizations',
  SERVER_GET_ORGANIZATION = 'server_getOrganization',
  SERVER_PLAYER_CREATE_ORGANIZATION = 'server_playerCreateOrganization',
  SERVER_GET_ORGANIZATION_MEMBERS = 'server_getOrganizationMembers',
  SERVER_ORGANIZATION_MEMBER_UNINVITE = 'server_organizationMemberUninvite',
  SERVER_ORGANIZATION_MEMBER_UPDATE = 'server_organizationMemberUpdate',
  SERVER_CREATE_ORGANIZATION_RANK = 'server_createOrganizationRank',
  SERVER_ORGANIZATION_MEMBER_INVITE = 'server_organizationMemberInvite',
  SERVER_ORGANIZATION_RANK_DELETE = 'server_organizationRankDelete',
  BROWSER_SET_ORGANIZATION_ID = 'browser_setOrganizationId',
  SERVER_ORGANIZATION_RANK_UPDATE = 'server_organizationRankUpdate',

  CLIENT_PLAYER_TOGGLE_NO_CLIP = 'client_playerToggleNoClip',

  BROWSER_SET_HANDHELD_RADIO = 'browser_setHandheldRadio',
  SERVER_HANDHELD_RADIO_UPDATE = 'server_handheldRadioUpdate',

  BROWSER_SET_BAN_INFO = 'browser_setBanInfo',

  SERVER_PROPERTY_CREATE = 'server_propertyCreate',
  BROWSER_SET_PROPERTY_INFO = 'browser_setPropertyInfo',
  BROWSER_SET_PROPERTY = 'browser_setProperty',
  CLIENT_TOGGLE_PROPERTY_INFO = 'client_togglePropertyInfo',
  SERVER_PROPERTY_LOCK = 'server_propertyLock',
  CLIENT_TOGGLE_PROPERTY_MENU = 'client_togglePropertyMenu',
  SERVER_PROPERTY_UPDATE = 'server_propertyUpdate',
  SERVER_PROPERTY_MAIN_INTERACTION = 'server_propertyMainInteraction',
  SERVER_CREATE_PROPERTY_POINT = 'server_createPropertyPoint',
  SERVER_UPDATE_PROPERTY_POINT = 'server_updatePropertyPoint',
  SERVER_DELETE_PROPERTY_POINT = 'server_deletePropertyPoint',

  SERVER_GET_COMMANDS = 'server_getCommands',

  BROWSER_SET_CURRENT_LOCATION = 'browser_setCurrentLocation',
  BROWSER_SET_SPEED_LIMIT = 'browser_setSpeedLimit',
  BROWSER_SET_PHONE_MESSAGES = 'browser_setPhoneMessages',
  BROWSER_ADD_PHONE_MESSAGE = 'browser_addPhoneMessage',
  CLIENT_PHONE_MAP_INIT = 'client_phoneMapInit',
  SERVER_TOGGLE_PHONE = 'server_togglePhone',
  BROWSER_SET_PHONE = 'browser_setPhone',
  CLIENT_PHONE_CAMERA_TOGGLE = 'client_phoneCameraToggle',
  SERVER_SEND_PHONE_MESSAGE = 'server_sendPhoneMessage',
  SERVER_UPDATE_PHONE_MESSAGE = 'server_updatePhoneMessage',
  SERVER_UPDATE_PHONE_SETTINGS = 'server_updatePhoneSettings',
  SERVER_CREATE_PHONE_CONTACT = 'server_createPhoneContact',
  SERVER_UPDATE_PHONE_CONTACT = 'server_updatePhoneContact',
  SERVER_DELETE_PHONE_CONTACT = 'server_deletePhoneContact',
  SERVER_UPDATE_PHONE_MESSAGES = 'server_updatePhoneMessages',
  CLIENT_PHONE_CAMERA_TAKE_PHOTO = 'client_phoneCameraTakePhoto',
  BROWSER_SET_PHONE_CALL = 'browser_setPhoneCall',
  SERVER_CREATE_PHONE_CALL = 'server_createPhoneCall',
  SERVER_ANSWER_PHONE_CALL = 'server_answerPhoneCall',
  SERVER_HANGUP_PHONE_CALL = 'server_hangupPhoneCall',
  SERVER_PHONE_UPDATE_NOTES = 'server_phoneUpdateNotes',
  SERVER_GET_BANK_ACCOUNT_BY_PHONE_NUMBER = 'server_getBankAccountByPhoneNumber',
  SERVER_GET_FORECAST = 'server_getForecast',
  SERVER_CREATE_ADVERTISEMENT = 'server_createAdvertisement',
  SERVER_GET_ADVERTISEMENTS = 'server_getAdvertisements',
  SERVER_GET_MY_ADVERTISEMENTS = 'server_getMyAdvertisements',
  SERVER_PHONE_ADD_PHOTO = 'server_phoneAddPhoto',
  SERVER_PHONE_DELETE_PHOTO = 'server_phoneDeletePhoto',

  BROWSER_CLEAR_CHAT = 'browser_clearChat',

  SERVER_GET_DRIVING_QUIZ = 'server_dmvGetQuiz',
  SERVER_FINISH_DRIVING_TEST = 'server_finishDrivingTest',
  CLIENT_START_DRIVING_TEST = 'client_startDrivingTest',
  SERVER_START_DRIVING_TEST = 'server_startDrivingTest',
  SERVER_ADD_DRIVING_TEST_MISTAKE = 'server_addDrivingTestMistake',

  SERVER_PLAYER_INVENTORY_GET_BANK_CARDS = 'server_playerInventoryGetBankCards',

  SERVER_PROPERTY_RENT_VEHICLE = 'server_propertyRentVehicle',
  SERVER_RETURN_RENT_VEHICLE = 'server_returnRentVehicle',
  SERVER_GROCERY_STORE_BUY = 'server_groceryStoreBuy',

  SERVER_GET_CATALOG_AVAILABLE_ITEMS = 'server_getCatalogAvailableItems',
  SERVER_CATALOG_ADD_PRODUCT = 'server_catalogAddProduct',
  SERVER_CATALOG_REMOVE_PRODUCT = 'server_catalogRemoveProduct',

  CLIENT_TOGGLE_CLOTHING_STORE = 'client_toggleClothingStore',
  CLIENT_CLOTHING_PREVIEW = 'client_clothingPreview',

  CLIENT_SCREENSHOT_CLOTHING = 'client_screenshotClothing',
  CLIENT_SCREENSHOT_ITEM_OBJECTS = 'client_screenshotItemObjects',
  CLIENT_GET_DRAWABLE_VARIATIONS = 'client_getComponentDrawableVariations',
  CLIENT_GET_PLAYER_MODEL = 'client_getPlayerModel',
  CLIENT_GET_TEXTURE_VARIATIONS = 'client_getComponentTextureVariations',
  SERVER_CLOTHING_STORE_BUY = 'server_clothingStoreBuy',

  CLIENT_TOGGLE_DEALERSHIP_MENU = 'client_toggleDealershipMenu',
  CLIENT_PREVIEW_VEHICLE_MODEL = 'client_previewVehicleModel',
  SERVER_VEHICLE_DEALERSHIP_BUY = 'server_vehicleDealershipBuy',

  CLIENT_TOGGLE_PLAYER_MENU = 'client_togglePlayerMenu',
  SERVER_GET_PLAYER_ACCOUNT = 'server_getPlayerAccount',
  SERVER_GET_PLAYER_CHARACTER = 'server_getPlayerCharacter',
  SERVER_GET_PLAYER_PROPERTIES = 'server_getPlayerProperties',
  SERVER_GET_PLAYER_VEHICLES = 'server_getPlayerVehicles',
  SERVER_VEHICLE_LOAD = 'server_vehicleLoad',
}
