export enum GameUiKey {
  Authorization = 'authorization',
  CharacterCreator = 'characterCreator',
  BanInfo = 'banInfo',
  Hud = 'hud',
  VehicleHud = 'vehicleHud',
  Inventory = 'inventory',
  PlayerMenu = 'playerMenu',
  Offer = 'offer',
  BankMenu = 'bankMenu',
  ATM = 'atm',
  AnimationMenu = 'animationMenu',
  DeathScreen = 'deathScreen',
  DamageInfo = 'damageInfo',
  CreateOrganization = 'createOrganization',
  ManageOrganization = 'manageOrganization',
  CreateProperty = 'createProperty',
  PropertyInfo = 'propertyInfo',
  ManageProperty = 'manageProperty',
  HandheldRadio = 'handheldRadio',
}
