export const enum AnimationFlag {
   NORMAL = 0,
   REPEAT = 1,
   STOP_LAST_FRAME = 2,
   UPPERBODY_ONLY = 16,
   ENABLE_PLAYER_CONTROL = 32,
   UPPERBODY_ONLY_CONTROLLABLE = 49,
   UPPERBODY_STOP_ON_LAST_FRAME_CONTROLLABLE = 50,
   CANCELABLE = 120,
}
