export const enum AnimationFlag {
   NORMAL = 0,
   REPEAT = 1,
   STOP_LAST_FRAME = 2,
   NOT_INTERRUPTABLE = 8,
   UPPER_BODY_ONLY = 16,
   ENABLE_PLAYER_CONTROL = 32,
   UPPER_BODY_ONLY_CONTROLLABLE = 49,
   UPPER_BODY_STOP_ON_LAST_FRAME_CONTROLLABLE = 50,
   CANCELABLE = 120,
}
