export const enum PlayerSharedDataType {
  Username = 'username',
  CharacterId = 'character_id',
  TextBubble = 'text_bubble',
  IsSpawned = 'is_spawned',
  IsCuffed = 'is_cuffed',
  MutedUntil = 'muted_until',
  Cash = 'cash',
  IsWounded = 'state',
  SelectedItemId = 'selected_item_id',
  Administrator = 'administrator',
  Animation = 'animation',
  Attachments = 'attachments',
  Frozen = 'frozen',
  Offer = 'offer',
  ClickToUse = 'click_to_use',
  HighlightTarget = 'highlight_target',
  WalkingStyle = 'walking_style',
  AdminDuty = 'admin_duty',
  Organization = 'organization',
  PhoneState = 'phone_state',
  Afk = 'afk',
  Seatbelt = 'seatbelt',
  HoldingGarbage = 'holding_garbage',
  Job = 'job',
  Work = 'work',
  CharacterName = 'character_name',
}
