export interface HeadOverlayComponentDef {
  label: string;
  key: string;
  overlayId: number;
  values: string[];
  colors?: string[];
}

export const headOverlays: HeadOverlayComponentDef[] = [
  {
    label: 'Blemish',
    key: 'blemishes',
    overlayId: 0,
    values: [
      'Measles',
      'Pimples',
      'Spots',
      'Break Out',
      'Blackheads',
      'Build Up',
      'Pustules',
      'Zits',
      'Full Acne',
      'Acne',
      'Cheek Rash',
      'Face Rash',
      'Picker',
      'Puberty',
      'Eyesore',
      'Chin Rash',
      'Two Face',
      'T Zone',
      'Greasy',
      'Marked',
      'Acne Scarring',
      'Full Acne Scarring',
      'Cold Sores',
      'Impetigo'
    ]
  },
  {
    label: 'Eyebrows',
    key: 'eyebrows',
    overlayId: 2,
    values: [
      'Balanced',
      'Fashion',
      'Cleopatra',
      'Quizzical',
      'Femme',
      'Seductive',
      'Pinched',
      'Chola',
      'Triomphe',
      'Carefree',
      'Curvaceous',
      'Rodent',
      'Double Tram',
      'Thin',
      'Penciled',
      'Mother Plucker',
      'Straight and Narrow',
      'Natural',
      'Fuzzy',
      'Unkempt',
      'Caterpillar',
      'Regular',
      'Mediterranean',
      'Groomed',
      'Bushels',
      'Feathered',
      'Prickly',
      'Monobrow',
      'Winged',
      'Triple Tram',
      'Arched Tram',
      'Cutouts',
      'Fade Away',
      'Solo Tram',
      'None'
    ]
  },
  {
    label: 'Ageing',
    key: 'ageing',
    overlayId: 3,
    values: [
      'Crow\'s Feet',
      'First Signs',
      'Middle Aged',
      'Worry Lines',
      'Depression',
      'Distinguished',
      'Aged',
      'Weathered',
      'Wrinkled',
      'Sagging',
      'Tough Life',
      'Vintage',
      'Retired',
      'Junkie',
      'Geriatric'
    ]
  },
  {
    label: 'Makeup',
    key: 'makeup',
    overlayId: 4,
    values: [
      'Smoky Black',
      'Bronze',
      'Soft Gray',
      'Retro Glam',
      'Natural Look',
      'Cat Eyes',
      'Chola',
      'Vamp',
      'Vinewood Glamour',
      'Bubblegum',
      'Aqua Dream',
      'Pin up',
      'Purple Passion',
      'Smoky Cat Eye',
      'Smoldering Ruby',
      'Pop Princess',
      'Kiss My Axe',
      'Panda Pussy',
      'The Bat',
      'Skull in Scarlet',
      'Serpentine',
      'The Veldt',
      'Unknown 1',
      'Unknown 2',
      'Unknown 3',
      'Unknown 4',
      'Tribal Lines',
      'Tribal Swirls',
      'Tribal Orange',
      'Tribal Red',
      'Trapped in A Box',
      'Clowning',
      'Guyliner',
      'Unknown 5',
      'Blood Tears',
      'Heavy Metal',
      'Sorrow',
      'Prince of Darkness',
      'Rocker',
      'Goth',
      'Punk',
      'Devastated'
    ]
  },
  {
    label: 'Blush',
    key: 'blush',
    overlayId: 5,
    values: [
      'Full',
      'Angled',
      'Round',
      'Horizontal',
      'High',
      'Sweetheart',
      'Eighties'
    ]
  },
  {
    label: 'Complexion',
    key: 'complexion',
    overlayId: 6,
    values: [
      'Rosy Cheeks',
      'Stubble Rash',
      'Hot Flush',
      'Sunburn',
      'Bruised',
      'Alcoholic',
      'Patchy',
      'Totem',
      'Blood Vessels',
      'Damaged',
      'Pale',
      'Ghostly'
    ]
  },
  {
    label: 'Sun Damage',
    key: 'sunDamage',
    overlayId: 7,
    values: [
      'Uneven',
      'Sandpaper',
      'Patchy',
      'Rough',
      'Leathery',
      'Textured',
      'Coarse',
      'Rugged',
      'Creased',
      'Cracked',
      'Gritty'
    ]
  },
  {
    label: 'Lipstick',
    key: 'lipstick',
    overlayId: 8,
    values: [
      'Color Matte',
      'Color Gloss',
      'Lined Matte',
      'Lined Gloss',
      'Heavy Lined Matte',
      'Heavy Lined Gloss',
      'Lined Nude Matte',
      'Liner Nude Gloss',
      'Smudged',
      'Geisha'
    ]
  },
  {
    label: 'Freckles',
    key: 'molesFreckles',
    overlayId: 9,
    values: [
      'Cherub',
      'All Over',
      'Irregular',
      'Dot Dash',
      'Over the Bridge',
      'Baby Doll',
      'Pixie',
      'Sun Kissed',
      'Beauty Marks',
      'Line Up',
      'Modelesque',
      'Occasional',
      'Speckled',
      'Rain Drops',
      'Double Dip',
      'One Sided',
      'Pairs',
      'Growth'
    ]
  },
  {
    label: 'Chest hair',
    key: 'chestHair',
    overlayId: 10,
    values: [
      'Natural',
      'The Strip',
      'The Tree',
      'Hairy',
      'Grisly',
      'Ape',
      'Hairy with Arms',
      'The Bikini',
      'Lightning Bolt',
      'Reverse Lightning',
      'Love Heart',
      'Chestache',
      'Happy Face',
      'Skull',
      'Snail Trail',
      'Slug and Nips',
      'Hairy Arms',
      'Shaved'
    ]
  }
];
