name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
   build:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Set up Node.js
       uses: actions/setup-node@v2
       with:
         node-version: '18'

     - name: Install dependencies
       run: npm add --global nx@latest

     - name: Install dependencies
       run: npm install

     - name: Build server
       run: nx run rage-server:build

     - name: Build client
       run: nx run rage-client:build:production

     - name: Build client UI
       run: nx run rage-ui:build

     - name: Set up Docker Build
       uses: docker/setup-buildx-action@v1

     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and push Docker image
       uses: docker/build-push-action@v2
       with:
         context: .
         push: true
         tags: zekiloni2/revolt_rp:latest

   deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to VPS
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SERVER_KEY }}
            debug: true
            script: |
              echo "Running commands on VPS"
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
              docker pull zekiloni2/revolt_rp:latest

              docker stop ragemp_server || true
              docker rm ragemp_server || true

              if [ -z "$(docker network ls --filter name=revolt_network -q)" ]; then
                echo "Creating Docker network revolt_network..."
                docker network create revolt_network
              else
                echo "Docker network revolt_network already exists."
              fi

              if [ "$(docker ps -q -f name=mongo_db)" ]; then
                echo "MongoDB is already running."
              else
                echo "Running MongoDB container with authentication enabled..."

                docker pull mongo:latest
                docker run -d --name mongo_db \
                  --network revolt_network \
                  -p 27017:27017 \
                  -v mongo_data:/data/db \
                  -e MONGO_INITDB_ROOT_USERNAME=${{ secrets.DATABASE_ROOT_USERNAME }} \
                  -e MONGO_INITDB_ROOT_PASSWORD=${{ secrets.DATABASE_ROOT_PASSWORD }} \
                  mongo:latest --auth
              fi

              docker run -d --name ragemp_server \
               --network revolt_network \
               -p 22005:22005/udp -p 22005:22005/tcp -p 22006:22006/tcp \
               -e DATABASE_URL="mongodb://${{ secrets.DATABASE_ROOT_USERNAME }}:${{ secrets.DATABASE_ROOT_PASSWORD }}@mongo_db:27017/revolt_rp" \
               zekiloni2/revolt_rp:latest

              echo "Deployment finished."
