name: RAGE:MP Server CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'packages/rage-ui/**'
      - 'packages/rage-client/**'
      - 'packages/rage-server/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/rage-ui/**'
      - 'packages/rage-client/**'
      - 'packages/rage-server/**'

jobs:
   build:
     runs-on: ubuntu-latest
     env:
       IMAGE_NAME: ghcr.io/zekiloni/revolt-rp/web-api
     steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '18'

     - name: Install dependencies
       run: npm ci

     - name: Build RAGE:Server
       run: npx nx run rage-server:build

     - name: Build RAGE:Client
       run: npx nx run rage-client:build:production

     - name: Build RAGE:Client-UI
       run: npx nx run rage-ui:build:production

     - name: Set up Docker Build
       uses: docker/setup-buildx-action@v3

     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_ACCESS_TOKEN }}
         registry: ghcr.io

     - name: Build and push Docker image
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: ${{ env.IMAGE_NAME }}:latest

   deploy:
      runs-on: ubuntu-latest
      env:
        IMAGE_NAME: ghcr.io/zekiloni/revolt-rp/ragemp
      needs: build
      steps:
        - name: Deploy to VPS
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            key: ${{ secrets.SERVER_KEY }}
            debug: true
            timeout: 60s
            known_hosts: |
              ${{ secrets.KNOWN_HOSTS }}
            script: |
              echo "Running commands on VPS"
              echo "${{ secrets.GHCR_ACCESS_TOKEN }}" | docker login ghcr.io --username ${{ github.actor }} --password-stdin

              docker stop ragemp_server || true
              docker rm ragemp_server || true

              docker images "${{ env.IMAGE_NAME }}" -q | xargs -I {} docker rmi -f {}
              docker pull ${{ env.IMAGE_NAME }}:latest

              if [ -z "$(docker network ls --filter name=revolt_network -q)" ]; then
                echo "Creating Docker network revolt_network..."
                docker network create revolt_network
              else
                echo "Docker network revolt_network already exists."
              fi

              if [ "$(docker ps -q -f name=mongo_db)" ]; then
                echo "MongoDB is already running."
              else
                echo "Running MongoDB container with authentication enabled..."

                if [ "$(docker ps -aq -f name=mongo_db)" ]; then
                  echo "Stopping and removing existing MongoDB container..."
                  docker stop mongo_db || true
                  docker rm mongo_db || true
                fi

                docker pull mongo:latest
                docker run -d --name mongo_db \
                  --network revolt_network \
                  -p 27017:27017 \
                  -v mongo_data:/data/db \
                  mongo:latest
              fi

              docker run -d --name ragemp_server \
               --network revolt_network \
               -p 22005:22005/udp -p 22005:22005/tcp -p 22006:22006/tcp \
               -e DATABASE_URL="mongodb://mongo_db:27017/revolt_rp" \
               "${{ env.IMAGE_NAME }}:latest"

              echo "Deployment finished."
